/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.refactorlabs.cs378;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum ImpressionType { 
  ACTION, VDP, SRP  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ImpressionType\",\"namespace\":\"com.refactorlabs.cs378\",\"symbols\":[\"ACTION\",\"VDP\",\"SRP\"],\"default\":\"SRP\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
