/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.refactorlabs.cs378;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum Vertical { 
  CARS, NONE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Vertical\",\"namespace\":\"com.refactorlabs.cs378\",\"symbols\":[\"CARS\",\"NONE\"],\"default\":\"NONE\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
