/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.refactorlabs.cs378;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum BidType { 
  LEAD, SALE, OTHER  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"BidType\",\"namespace\":\"com.refactorlabs.cs378\",\"symbols\":[\"LEAD\",\"SALE\",\"OTHER\"],\"default\":\"LEAD\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
