/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.refactorlabs.cs378.sessions;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum LeadType { 
  GOOD, DUPLICATE, RANGE, ERROR, BAD  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"LeadType\",\"namespace\":\"com.refactorlabs.cs378.sessions\",\"symbols\":[\"GOOD\",\"DUPLICATE\",\"RANGE\",\"ERROR\",\"BAD\"],\"default\":\"BAD\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
