/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.refactorlabs.cs378;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum ActiveX { 
  ENABLED, NOT_SUPPORTED, DISABLED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ActiveX\",\"namespace\":\"com.refactorlabs.cs378\",\"symbols\":[\"ENABLED\",\"NOT_SUPPORTED\",\"DISABLED\"],\"default\":\"NOT_SUPPORTED\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
